In [4]:
import numpy as np

def quanten_matching(
    complete_pc_matrices_per_shape_class: list[np.matrix], k: int
) -> None:

    n = len(complete_pc_matrices_per_shape_class)
    all_probs = []
    for i in range(n):
        pc_matrix = complete_pc_matrices_per_shape_class[i]
        print(f"{pc_matrix = }")
        squared_pc_matrix = pc_matrix**2
        print(f"{squared_pc_matrix = }")
        prob = np.sum(squared_pc_matrix[:, :k], axis=1)
        print(f"{prob = }")
        all_probs.append(prob)
        print("---")

    probability_matrix = np.array(all_probs)
    print(f"{probability_matrix=}")
    
    for vec in  probability_matrix.T:
        _,arr  = np.unique(vec, return_counts=True) 
        if np.max(arr) > 1: 
            print("problem!!!")

    targeted_shape_class = np.argmax(
        probability_matrix, axis=0
    )  # Gibt Index des größten Wertes in einer Spalte
    return targeted_shape_class


X = np.array([[1,1,5],[0,3,1],[1,0,0]])
Y = np.array([[2,1,1],[1,1,4],[1,0,0]])
quanten_matching(complete_pc_matrices_per_shape_class=[X,Y], k=1)

pc_matrix = array([[1, 1, 5],
       [0, 3, 1],
       [1, 0, 0]])
squared_pc_matrix = array([[ 1,  1, 25],
       [ 0,  9,  1],
       [ 1,  0,  0]])
prob = array([1, 0, 1])
---
pc_matrix = array([[2, 1, 1],
       [1, 1, 4],
       [1, 0, 0]])
squared_pc_matrix = array([[ 4,  1,  1],
       [ 1,  1, 16],
       [ 1,  0,  0]])
prob = array([4, 1, 1])
---
probability_matrix=array([[1, 0, 1],
       [4, 1, 1]])
problem!!!


array([1, 1, 0])

In [2]:
import numpy as np
A = np.array([[1,2,3],[4,5,6]])
A[0][1]
np.sum(A[1])
A**2

array([[ 1,  4,  9],
       [16, 25, 36]])

In [9]:
import numpy as np

a = np.array([1,2,3,2, 3, 2])
np.sum([a == 3])

2

In [33]:
import numpy as np

X = np.array([[1,2,3,4], [2,3,4,3]])
m = np.array([5,6,7,8])
X[:, -1] = np.array([1,1])
print(X)
print([5]*2)

[[1 2 3 1]
 [2 3 4 1]]
[5, 5]


In [20]:
import numpy as np

A = np.array([[1,1,2], [2,0,2], [1,2,3]])
print(np.linalg.eigh(A.T@A))

v1 = np.array([1.0, 2.0, 3.0])
v2 = np.array([2.0, 4.0, 1.0])
v3 = np.array([1.0, 0.0, 2.0])
V = np.array([v1, v2, v3])
print(V)

(array([2.14369254e-16, 2.46743741e+00, 2.55325626e+01]), array([[ 0.57735027,  0.69126815, -0.43452849],
       [ 0.57735027, -0.72194678, -0.38139154],
       [-0.57735027, -0.03067863, -0.81592003]]))
[[1. 2. 3.]
 [2. 4. 1.]
 [1. 0. 2.]]


In [34]:
import numpy as np

x1 = np.array([1, 2])
x2 = np.array([-1, 1])

X = np.array([x1,x2])
print(X)
mX = np.mean(X, axis=0)
print(mX)
XX =X - mX
print(XX)
print(np.cov(XX.T))

[[ 1  2]
 [-1  1]]
[0.  1.5]
[[ 1.   0.5]
 [-1.  -0.5]]
[[2.  1. ]
 [1.  0.5]]
